// books
export const GET_BOOKS = 'GET_BOOKS';
export const GET_SINGLE_BOOK = 'GET_SINGLE_BOOK';
export const GET_BOOKS_BY_CATEGORY = 'GET_BOOKS_BY_CATEGORY';
export const CREATE_BOOK = 'CREATE_BOOK';
export const UPDATE_BOOK = 'UPDATE_BOOK';
export const UPDATE_ACTIVE_BOOK = 'UPDATE_ACTIVE_BOOK';
export const REMOVE_BOOK = 'REMOVE_BOOK';

// categories
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';

// comments
export const GET_BOOK_COMMENTS = 'GET_BOOK_COMMENTS';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';